import { Agency } from "./agency.interface";
import { Author } from "./author.interface";
import { Caption } from "./caption.interface";
import { Category } from "./category.interface";
import { KeywordsList } from "./keywords-list.interface";
import { Preview } from "./preview.interface";
import { TagList } from "./tag-list.interface";

export interface PhotoDetails {
	agency:                Agency;
	api_ftp:               null;
	aspect_ratio:          number;
	author:                Author;
	author_id:             number;
	caption:               Caption[];
	caption_suffix:        string;
	category:              Category;
	currency:              string;
	date_created:          Date;
	date_imported:         Date;
	editing_lock:          null;
	file_name:             string;
	gallery_id:            number;
	has_preview:           boolean;
	headline:              Caption[];
	id:                    string;
	is_special_offer:      boolean;
	keywords_list:         KeywordsList[];
	kind:                  string;
	licences:              any[];
	media_id:              number;
	needs_translation:     boolean;
	notes:                 string[];
	people_list:           any[];
	preview:               Preview;
	preview_url:           null;
	preview_url_blur:      null;
	preview_url_large:     null;
	print_price:           null;
	product_name:          string;
	seo_url:               string;
	special_offer_type:    null;
	special_offer_types:   any[];
	tag_list:              TagList[];
	var_large_description: string;
	var_large_name:        string;
	var_large_price:       string;
	var_small_description: string;
	var_small_name:        string;
	var_small_price:       string;
	video_title:           Caption[];
	web_price:             null;
}